language: ruby
matrix:
  include:
    - env: OSX=10.15.5
      os: osx
      osx_image: xcode12.2
    - env: OSX=10.14.6
      os: osx
      osx_image: xcode11.3
#    - os: linux
#      dist: focal

before_install:
  - brew update

install:
  - mkdir -p $(brew --repo)/Library/Taps/travis
  - ln -s $PWD $(brew --repo)/Library/Taps/travis/homebrew-testtap
  - brew tap --repair

script:
  - brew audit --new-formula jenkins-slave.rb || true # sometimes it fails because of GitHub API Error: API rate limit exceeded for
  - brew install jenkins-slave
  - brew test jenkins-slave
  - brew uninstall jenkins-slave

addons:
  ssh_known_hosts: github.com
